### PR TITLE
enabled a *pure* contour where fd is not applied to the weights

### PR DESCRIPTION
**Pull request by cortner**
I needed weights that don't incorporate the fermi-dirac function.

### CODE REVIEW

**Comment by cortner** [comment]
actually - please wait before (testing and) merging, I should run some tests first.

**Comment by ettersi** [comment]
In this case, it might be easier to remove the Fermi-Dirac weights altogether, and provide another function to give the weights instead.

**Comment by cortner** [comment]
I can do that if course.

**Comment by cortner** [comment]
this seems to work for me now. (except for a related but distinct issue that I'll explain elsewhere)

**Pull request merged**
